# Site settings
title: Paul Steppacher
description: Resumee
# baseurl: "" # the subpath of your site, e.g. /blog
url: "https://github.com/how-about-this/how-about-this:8080" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: Paul Steppacher
user_description: I am a IT Consultant currently focusing on becoming a Software Developer with emphasis on Data Analysis
user_title: IT Consultant/Developer
email: p.steppacher91@gmail.com
# twitter_username: lorem_ipsum
github_username:  how-about-this
# gplus_username:  lorem_ipsum

# Google-analytics
google-analytics:
  id: ""

exclude: ['package.json', 'node_modules']
