# Site settings
title: Philipp Merz
description: Resumee
# baseurl: "" # the subpath of your site, e.g. /blog
# url: "https://github.com/metaconsole/online_cv:8080" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: Philipp Merz
user_description: I'm a IT Consultant focusing on Data Science and Sotfware Development.
user_title: IT Consultant and Data Scientist
email: merz-philipp@web.de
# twitter_username: keinen_twitter_handle
github_username:  metaconsole
# gplus_username:  metaconsole

# Google-analytics
google-analytics:
  id: ""

exclude: ['package.json', 'node_modules']

theme: jekyll-theme-minimal
